### ISSUE TITLE
fujprog always fails the first time with icestation32

### ISSUE THREAD

**Issue by vmedea** [kost/fujprog#11] opened 2020-10-17 14:00 UTC
While trying to write to flash with `fujprog` while icestation32 is running it always fails the first time with `Received and expected data do not match!` and a mismatch. The second time it always works:
```
ubuntu@build:~/icestation-32/software/sprites$ make ulx3s_prog
Building gfx_convert if needed
Building header_gen if needed
../common/../../utilities/gfx_convert/gfx_convert -f png -o crystal_ crystal.png
Found paletted image
Palette size: 16
../common/../../utilities/header_gen/header_gen -t uint16_t -s -i crystal_tiles -o ./crystal_tiles crystal_tiles.bin
../common/../../utilities/header_gen/header_gen -t uint16_t -s -i crystal_palette -o ./crystal_palette crystal_palette.bin
riscv-none-embed-cpp -P -o sections_p.lds ../common/sections.lds
riscv-none-embed-gcc -std=c11 -Wall -Os -MMD -MP -flto -march=rv32i -mabi=ilp32 -I../common/../common/ -I../common/../lib/ -I./ -ffreestanding -nostdlib -DASSERT_ENABLED -c main.c -o main.o
riscv-none-embed-gcc -std=c11 -Wall -Os -MMD -MP -flto -march=rv32i -mabi=ilp32 -I../common/../common/ -I../common/../lib/ -I./ -ffreestanding -nostdlib -DASSERT_ENABLED -c crystal_tiles.c -o crystal_tiles.o
riscv-none-embed-gcc -std=c11 -Wall -Os -MMD -MP -flto -march=rv32i -mabi=ilp32 -I../common/../common/ -I../common/../lib/ -I./ -ffreestanding -nostdlib -DASSERT_ENABLED -c crystal_palette.c -o crystal_palette.o
riscv-none-embed-gcc -std=c11 -Wall -Os -MMD -MP -flto -march=rv32i -mabi=ilp32 -I../common/../common/ -I../common/../lib/ -I./ -ffreestanding -nostdlib -DASSERT_ENABLED -Wl,-Bstatic,-T,sections_p.lds,--strip-debug main.o crystal_tiles.o crystal_palette.o ../lib/vdp.o ../lib/math_util.o ../common/font.o     ../common/vectors.o ../common/start.o -o prog.elf -lgcc
riscv-none-embed-objcopy -O binary prog.elf prog.bin

fujprog -j flash -f 0x200000 prog.bin
ULX2S / ULX3S JTAG programmer v4.8 (git f498967 built Oct  8 2020 16:06:36)
Copyright (C) Marko Zec, EMARD, gojimmypi, kost and contributors
Using USB cable: ULX3S FPGA 85K v3.0.8
Erasing sectors, please wait.
Type, paste or pipe your bitstream.
Programming: 0% \ Received and expected data do not match!
TDO: 0000 Expected: 4000 mask: C100
Line 26: Operation not permitted

Failed.
ubuntu@build:~/icestation-32/software/sprites$ make ulx3s_prog
Building gfx_convert if needed
Building header_gen if needed

fujprog -j flash -f 0x200000 prog.bin
ULX2S / ULX3S JTAG programmer v4.8 (git f498967 built Oct  8 2020 16:06:36)
Copyright (C) Marko Zec, EMARD, gojimmypi, kost and contributors
Using USB cable: ULX3S FPGA 85K v3.0.8
Erasing sectors, please wait.
Type, paste or pipe your bitstream.
Programming: 100%
Completed in 80.57 seconds.
```
It does nothing special with regard to arguments (`-j flash -f 0x200000`, fwiw it also happens at offset `0x0`).

It appears to me that something is interfering with programming. After the first time the device is in a reset state, and so the second time it works.

This is on a ULX3S 85F v3.0.8, with commit f498967.

**Comment by kost** [comment] 2020-10-19 04:14
Thanks on your report. Can you share prog.bin file for reproduction? 

Or it happens with any file?

**Comment by vmedea** [comment] 2020-10-19 08:35
Sure! [icestation-bitstreams-ulx3s-85f.tar.gz](https://github.com/kost/fujprog/files/5400285/icestation-bitstreams-ulx3s-85f.tar.gz)

But yes it appears to happen for any file, at any flash offset, for both the hardware and software part (and for different software!). The only commonality is that the icestation bitstream is already running when starting `fujprog`.

FWIW when programming it through the ESP32 I haven't noticed any issue.

**Comment by vmedea** [comment] 2020-10-28 15:36
Just checked and `fujprog -j sram` does work in the same circumstances! This reaffirms what @dan-rodrigues mentioned on discord: ics32 sets the flash chip in CRM mode, and it possibly still is when `fujprog` starts programming and thus gets unexpected results.

**Comment by kost** [comment] 2020-10-29 07:08
Thanks for reporting. 

So, this only happens with this bitstream as I have tried with different bitstream (blink) and everything works correctly? 

It seems that ics32 is in CRM mode  because first time it works, second one when ics32 sets the CRM mode, I get this error:
```
$ sudo ../fujprog-v48-linux-x64 -j FLASH ulx3s.bit@0x0 
ULX2S / ULX3S JTAG programmer v4.8 (git 96ebb45 built Oct  7 2020 20:34:11)
Copyright (C) Marko Zec, EMARD, gojimmypi, kost and contributors
Using USB cable: ULX3S FPGA 85K v3.0.8
Could not automatically guess type by extension: @0x0.
Automatically targeting flash and setting image type.
Erasing sectors, please wait.
Programming: 100%  
Completed in 64.67 seconds.
$ sudo ../fujprog-v48-linux-x64 -j FLASH ulx3s.bit@0x0 
ULX2S / ULX3S JTAG programmer v4.8 (git 96ebb45 built Oct  7 2020 20:34:11)
Copyright (C) Marko Zec, EMARD, gojimmypi, kost and contributors
Using USB cable: ULX3S FPGA 85K v3.0.8
Could not automatically guess type by extension: @0x0.
Automatically targeting flash and setting image type.
Erasing sectors, please wait.
Programming: 0% - Received and expected data do not match!
TDO: 0000 Expected: 4000 mask: C100
Line 26: Operation not permitted

Failed.
```
and second time, it works (as expected):

```
sudo ../fujprog-v48-linux-x64 -j FLASH ulx3s.bit@0x0 
ULX2S / ULX3S JTAG programmer v4.8 (git 96ebb45 built Oct  7 2020 20:34:11)
Copyright (C) Marko Zec, EMARD, gojimmypi, kost and contributors
Using USB cable: ULX3S FPGA 85K v3.0.8
Could not automatically guess type by extension: @0x0.
Automatically targeting flash and setting image type.
Erasing sectors, please wait.
Programming: 100%  
Completed in 60.43 seconds.
```

So, fix for this would be to check if flash chip is in CRM mode and if it is - return from it? Need to investigate how to perform that. If you have any tips & tricks, feel free to share it.

**Comment by vmedea** [comment] 2020-10-29 09:22
Thanks, glad that you could reproduce it.

> So, this only happens with this bitstream as I have tried with different bitstream (blink) and everything works correctly?

I think so! I'm not aware of any other bitstreams that reproduce this. But haven't tried that many I mostly cycle between SaxonSoc, ICS32 and passthru at the moment :slightly_smiling_face: 

> So, fix for this would be to check if flash chip is in CRM mode and if it is - return from it? Need to investigate how to perform that. If you have any tips & tricks, feel free to share it.

That sounds like it would work. I think the best would be, if possible, to reset the flash chip thoroughly so that programming always starts from a deterministic state. I don't know if a flash chip has other state that could cause similar issues.

And I don't know much about flash programming internals at all to be honest, last time I looked into `fujprog` (and `ecp5.py` for that matter) it was a bit abracadabra to me :blush: Anything JTAG has so many levels of nesting. But if no one beats me to it I might dive in at some point.

At the moment I'm trying to reduce the number of times I flash things, avoid flashing where possible, because at this rate I'll burn out the board's flash before anything else.

**Comment by vmedea** [comment] 2020-10-31 20:51
See #12

**Closed** 2020-11-10 06:22 UTC
